### ISSUE TITLE
[please] the gigaherzcommon.jar needs to be external

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Guidebook#36] opened 2018-03-28 20:35 UTC
![e1d823517e3735f7979dbfe04fcca3b2](https://user-images.githubusercontent.com/3880072/38054762-7cef1b46-329d-11e8-806c-6c25aa65239a.png)

I'm getting really tired of having to remember to remove your core library everytime I update my modpack.

**Comment by gigaherz** [comment] 2018-03-28 20:58
I'm NOT making it external. That would defeat all that I'm trying to achieve by doing that. If it's so much of a problem (even though the people from curse said that their modpack creation tools in the twitch app should be warning you about this before you upload), I might consider going back to shading instead of embedding. That however means that each mod jar will contain a duplicate of the code, which is not ideal.

**Comment by kreezxil** [comment] 2018-03-29 00:04
The twitchapp doesn't warn anymore which is the problem then.

**Comment by PiggyClone205** [comment] 2018-06-03 18:41
Perhaps that bug should be reported to the twitchapp team, if that's the case.

**Comment by kreezxil** [comment] 2018-06-04 12:44
turns out the FORGE team applied some kind of patch that takes all extra
files such as yours and places them in a folder called "memory repo". Now
it is simply a matter unchecking that before exporting.

**Closed** 2018-06-14 16:18 UTC
