### ISSUE TITLE
Crash on 1.10 probably with advanced rocketry

### ISSUE THREAD

**Issue by gdarai** [gigaherz/Guidebook#33] opened 2018-02-10 10:38 UTC
Hi,
It looks like the guidebook has some issue rendering 
`<stack item="advancedrocketry:pressureTank" x="60"/>`

Here is the link to the issue in my modpack's github... containing the stacktrace and the guidebook xml file:
https://github.com/gdarai/SpaceRace/issues/14

**Comment by gigaherz** [comment] 2018-02-15 22:49
Hello, sorry that I didn't notice this issue earlier. Taking a quick look at the stack trace, I'm calling GuiScreen#renderTooltip with whatever itemstack is provided, and that seems to cause the crash.

Now, since I just create a "default" stack of that item, and everything else is done by the vanilla renderTooltip function, I have to conclude that it's an issue in advanced rocketry, which isn't protected against drawing tooltips of itemstacks that don't have the expected NBT. I can't do anything to fix it from my end. 
I can prevent the crash from bubbling up and closing the game, but this is a function that will be called every frame, for as long as the cursor is on top of the item in the book, meaning it would spam the log badly, unless I mark the internal "stack" element as failed so that I don't try to render again. As you may understand, this is a bit more work than I'm interested in doing for the 1.10.2 (or 1.11.2) versions, at this point...

**Comment by gigaherz** [comment] 2018-02-15 23:04
Unless... the stack itself is null... I'll take a look tomorrow, just in case.

**Comment by gigaherz** [comment] 2018-02-16 21:06
After some investigation, I believe I know the exact issue: Advanced Rocketry handles the case where the itemstack has the NBT data set to null, but not the case where the itemstack has the NBT data not null, but not the case where it's not null, but doesn't contain the information needed to get the tank info.

You can reproduce this same crash by taking an empty tank, and giving it a name in an anvil.

I recommend that you submit a bug report to them, with this information.

**Closed by gigaherz** 2018-02-16 21:06 UTC

**Comment by gdarai** [comment] 2018-02-19 13:27
Great info.. I will let them know. thanks.
